#!/usr/bin/env python

###  example agent output: #################################################################
#
# <<<backuppc_report>>>
#warn_flags,backup_number,host_name,date_time,size_mb,lvl,duratation_min,xfer_err,share_err,file_err,tar_err,age_days
#,184,host1,2019-07-24 01:45,3483,1,0,0,0,0,0,22
#,185,host1,2019-07-25 01:08,3481,1,1,0,0,0,0,21
#,186,host1,2019-07-26 01:07,3486,1,2,0,0,0,0,20
#,187,host1,2019-07-27 01:19,3501,0,16,0,0,0,0,19
#,188,host1,2019-07-28 01:02,3506,1,1,0,0,0,0,18
#,190,host2,2019-07-24 01:01,4909,1,3,0,0,0,0,22
#,191,host2,2019-07-25 01:00,4835,1,3,0,0,0,0,21
#,192,host2,2019-07-26 01:02,4864,0,4,0,0,0,0,20
#,193,host2,2019-07-27 01:09,4805,1,12,0,0,0,0,19
#E,67,host3,2019-08-09 18:15,86918,1,7,5,0,0,5,6
#E,68,host3,2019-08-10 18:00,86806,1,8,3,0,0,3,5
#,70,host3,2019-08-10 20:42,86780,1,2,0,0,0,0,4
#E,72,host3,2019-08-11 18:48,86890,1,8,3,0,0,3,4
#E,73,host3,2019-08-12 17:41,86934,1,11,3,0,0,3,3
#E,74,host3,2019-08-14 19:02,87159,1,31,3,0,0,3,1
#ED,75,host3,2019-08-15 19:02,86925,1,10,3,0,0,3,0
#
#
# run check from cli 
# cmk --checks=backuppc_report -I <hostname>
# cmk --checks=backuppc_report -nvp <hostname>
#
############################################################################################


############################################################################################
# INVENTORY FUNCTION 
############################################################################################
def inventory_backuppc_report(info):
    last_host=str()
    current_host=str()
    for line in info:
        # skip header line
        if 'warn_flags,backup_number,host_name' in line[0]:
            continue

        # if a new host is detected yield it
        current_host=str(line[0]).split(',')[2]
        if current_host != last_host:
            last_host=current_host
            yield current_host, None

    yield '- Summary', None




############################################################################################
# CHECK FUNCTION
############################################################################################
def check_backuppc_report(item, params, info):
    # use check_backuppc_summary function for summary report
    if item == '- Summary':
        return check_backuppc_summary(item, params, info)

    # handle backup hosts
    current_host=str()
    for line in info:
        # skip header line
        if 'warn_flags,backup_number,host_name' in line[0]:
            continue
    
        #print ' '.join(line)
    #print "item: " + str(item)
    #print "parems: " + str(params)
    #print "info:" + str(info)
    return 3, "Sorry - not implemented"


def check_backuppc_summary(item, params, info):
    host_count = 0
    host_progress_count = 0
    host_partial_count = 0
    host_error_count = 0
    host_toold_count = 0
    host_disabled_count = 0
    host_totalbkp_count = len(info) - 1 # ignore header line

    current_host=str()
    for line in info:
        if current_host != str(line[0]).split(',')[2]:
            current_host = str(line[0]).split(',')[2]
            host_count += 1

        warn_flag = str(line[0]).split(',')[0]
        if '*' in warn_flag:
            host_progress_count += 1
        if 'P' in warn_flag:
            host_partial_count += 1
        if 'E' in warn_flag:
            host_error_count += 1
        if 'O' in warn_flag:
            host_toold_count += 1
        if 'D' in warn_flag:
            host_disabled_count += 1


    print "host_count: " + str(host_count)
    print "host_progress_count: " + str(host_progress_count)
    print "host_partial_count: " + str(host_partial_count)
    print "host_error_count: " + str(host_error_count)
    print "host_toold_count: " + str(host_toold_count)
    print "host_disabled_count: " + str(host_disabled_count)

    return 3, "Sorry - not implemented summary"


############################################################################################
# DEFINE CHECK
############################################################################################ 
check_info["backuppc_report"] = {
    'check_function':            check_backuppc_report,
    'inventory_function':        inventory_backuppc_report,
    'service_description':       'BackupPC %s' 
}

